name: image

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      name:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ inputs.name }}
    # Skip running release workflow on forks
    if: github.repository_owner == '1mr'
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Login to DockerHub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: ${{ inputs.context }}
          push: true
          provenance: false
          tags: |
            ${{ inputs.name }}:${{ inputs.tag }}
            ${{ inputs.name }}:latest
