name: Docker Image CI

on:
  push:
    branches: [ master ]
  
jobs:

  build-debian-images:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        debian-version: ['buster', 'stretch']

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -f docker-base-images/debian/${{ matrix.debian-version }}/Dockerfile -t debian:${{ matrix.debian-version }} .
    - name: Upload image to GH registry
      run: |
        echo ${GH_TOKEN} | docker login -u ${GH_USER} ghcr.io --password-stdin
        docker push debian:${{ matrix.debian-version }}
