name: Docker Image CI

on:
  push:
    branches: [ master ]
  
jobs:

  build-debian-images:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        debian-version: ['buster', 'stretch']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker-base-images/debian/${{ matrix.debian-version }}/Dockerfile
        push: true
        tags: debian:${{ matrix.debian-version }}
    - name: Upload image to GH registry
      run: docker push debian:${{ matrix.debian-version }}
