name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  molecule-debian-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        debian-version: ['buster', 'bullseye']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker-base-images/debian/molecule/${{ matrix.debian-version }}/
          file: ./docker-base-images/debian/molecule/${{ matrix.debian-version }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/debian:molecule-${{ matrix.debian-version }}

  pgbpouncer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./pgbouncer/
          file: ./pgbouncer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pgbouncer:1.22.1
